import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = resolve(root, 'src/horses.generated.ts')
const userAgent = 'Mozilla/5.0 (compatible; HKHorseMemoryDataUpdater/1.0)'

const sources = [
  {
    key: 'two',
    length: 2,
    minimum: 100,
    url: 'https://racing.hkjc.com/zh-hk/local/information/selecthorsebychar?ordertype=2',
  },
  {
    key: 'three',
    length: 3,
    minimum: 200,
    url: 'https://racing.hkjc.com/zh-hk/local/information/selecthorsebychar?ordertype=3',
  },
  {
    key: 'four',
    length: 4,
    minimum: 700,
    url: 'https://racing.hkjc.com/zh-hk/local/information/selecthorsebychar?ordertype=4',
  },
]

const decodeHtml = (value) => value
  .replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
  .replace(/&#(\d+);/g, (_, decimal) => String.fromCodePoint(Number.parseInt(decimal, 10)))
  .replaceAll('&amp;', '&')
  .replaceAll('&quot;', '"')
  .replaceAll('&#39;', "'")
  .replaceAll('&lt;', '<')
  .replaceAll('&gt;', '>')

const parseHorses = (html, source) => {
  const pattern = /horseid=HK_\d{4}_([A-Z]\d+)[^>]*>([^<]+)<\/a>[\s\S]*?<td align="right" class=table_eng_text style="width: 52px; padding: 4px 3px; vertical-align: middle;">\s*(?:\((\d+)\))?\s*<\/td>/g
  const horses = []
  const seenCodes = new Set()

  for (const match of html.matchAll(pattern)) {
    const [, code, encodedName, ratingText] = match
    const name = decodeHtml(encodedName.trim())
    if (Array.from(name).length !== source.length || seenCodes.has(code)) continue
    seenCodes.add(code)
    horses.push({ name, code, rating: ratingText ? Number(ratingText) : null })
  }

  if (horses.length < source.minimum) {
    throw new Error(`${source.key}: parsed ${horses.length} horses; expected at least ${source.minimum}`)
  }

  const duplicateNames = horses.filter((horse, index) =>
    horses.findIndex((candidate) => candidate.name === horse.name) !== index)
  if (duplicateNames.length) {
    throw new Error(`${source.key}: duplicate horse names: ${duplicateNames.map((horse) => horse.name).join(', ')}`)
  }

  return horses
}

const checkPhoto = async (horse) => {
  const url = `https://racing.hkjc.com/general/-/media/Sites/JCRW/Horse_Images/${horse.code[0]}/${horse.code}_l.jpg`
  for (let attempt = 0; attempt < 2; attempt += 1) {
    try {
      const response = await fetch(url, {
        method: 'HEAD',
        redirect: 'follow',
        headers: { 'user-agent': userAgent },
      })
      if (response.status === 404) return false
      if (response.ok && response.headers.get('content-type')?.startsWith('image/')) return true
    } catch {
      // Retry once to avoid marking a portrait missing after a transient network failure.
    }
  }
  return false
}

const mapConcurrent = async (items, concurrency, mapper) => {
  const results = new Array(items.length)
  let cursor = 0

  const worker = async () => {
    while (cursor < items.length) {
      const index = cursor
      cursor += 1
      results[index] = await mapper(items[index], index)
    }
  }

  await Promise.all(Array.from({ length: concurrency }, worker))
  return results
}

const datasets = {}

for (const source of sources) {
  process.stdout.write(`Fetching ${source.key} horse list... `)
  const response = await fetch(source.url, { headers: { 'user-agent': userAgent } })
  if (!response.ok) throw new Error(`${source.key}: HKJC returned HTTP ${response.status}`)
  const horses = parseHorses(await response.text(), source)
  console.log(`${horses.length} names`)
  datasets[source.key] = horses
}

const allHorses = sources.flatMap((source) => datasets[source.key])
const allCodes = new Set(allHorses.map((horse) => horse.code))
if (allCodes.size !== allHorses.length) {
  throw new Error(`Duplicate brand codes found across lists (${allHorses.length - allCodes.size} duplicates)`)
}
console.log(`Checking portrait availability for ${allHorses.length} horses...`)
const photoFlags = await mapConcurrent(allHorses, 16, checkPhoto)
let photoIndex = 0

for (const source of sources) {
  datasets[source.key] = datasets[source.key].map((horse) => ({
    ...horse,
    hasPhoto: photoFlags[photoIndex++],
  }))
}

const generatedAt = new Date().toISOString()
const lines = [
  '// This file is generated by `npm run update:horses`.',
  `// Source snapshot: ${generatedAt}`,
  '// Do not edit manually.',
  '',
  'export const horseTuples = {',
]

for (const source of sources) {
  lines.push(`  ${source.key}: [`)
  for (const horse of datasets[source.key]) {
    lines.push(`    [${JSON.stringify(horse.name)}, ${JSON.stringify(horse.code)}, ${horse.rating ?? 'null'}, ${horse.hasPhoto}],`)
  }
  lines.push('  ],')
}

lines.push('} as const', '')
await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, lines.join('\n'), 'utf8')

for (const source of sources) {
  const horses = datasets[source.key]
  const photos = horses.filter((horse) => horse.hasPhoto).length
  const rated = horses.filter((horse) => horse.rating !== null).length
  console.log(`${source.key}: ${horses.length} total, ${photos} portraits, ${rated} rated`)
}

console.log(`Wrote ${outputPath}`)
